name: Lint Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    # - name: Initialize Terraform
    #   run: cd terraform && terraform init

    - name: Check Terraform formatting
      run: cd terraform && terraform fmt -check -recursive

    - name: Validate Terraform
      run: cd terraform && terraform validate